export const ColorScheme = [
    "hsl(0, 50%,   40%)",
    "hsl(0, 100%,  50%)",
    "hsl(30, 100%,  50%)",
    "hsl(55, 95%, 50%)",
    "hsl(100, 80%, 50%)",
    "hsl(190, 90%, 50%)",
    "hsl(230, 100%, 50%)",
    "hsl(280, 100%, 50%)",
    "hsl(320, 100%, 60%)",
    "hsl(0, 50%,   65%)",
    "hsl(0, 100%,  75%)",
    "hsl(30, 100%,  75%)",
    "hsl(55, 95%, 80%)",
    "hsl(100, 80%, 80%)",
    "hsl(190, 90%, 80%)",
    "hsl(230, 100%, 80%)",
    "hsl(280, 100%, 80%)",
    "hsl(320, 100%, 90%)",
    "hsl(0, 0%, 80%)",
];

export const Categories = [
    "Autos & Vehicles",
    "Comedy",
    "Education",
    "Entertainment",
    "Film & Animation",
    "Gaming",
    "Howto & Style",
    "Movies",
    "Music",
    "News & Politics",
    "Nonprofits & Activism",
    "People & Blogs",
    "Pets & Animals",
    "Science & Technology",
    "Shows",
    "Sports",
    "Trailers",
    "Travel & Events",
    "Not Specified",
];

export const CategoryColor = Object.freeze({
    [Categories[0]]: ColorScheme[0],
    [Categories[1]]: ColorScheme[1],
    [Categories[2]]: ColorScheme[2],
    [Categories[3]]: ColorScheme[3],
    [Categories[4]]: ColorScheme[4],
    [Categories[5]]: ColorScheme[5],
    [Categories[6]]: ColorScheme[6],
    [Categories[7]]: ColorScheme[7],
    [Categories[8]]: ColorScheme[8],
    [Categories[9]]: ColorScheme[9],
    [Categories[10]]: ColorScheme[10],
    [Categories[11]]: ColorScheme[11],
    [Categories[12]]: ColorScheme[12],
    [Categories[13]]: ColorScheme[13],
    [Categories[14]]: ColorScheme[14],
    [Categories[15]]: ColorScheme[15],
    [Categories[16]]: ColorScheme[16],
    [Categories[17]]: ColorScheme[17],
    [Categories[18]]: ColorScheme[18],
});

export const Countries = ["FR", "DE", "GB", "IN", "JP", "KR", "MX", "RU", "US", "CA"];

export const CountryCodeOf = Object.freeze({
    France: "FR",
    Germany: "DE",
    "United Kingdom": "GB",
    India: "IN",
    Japan: "JP",
    "South Korea": "KR",
    Mexico: "MX",
    Russia: "RU",
    "United States of America": "US",
    Canada: "CA",
});

export const CountryNameOf = Object.freeze({
    FR: "France",
    DE: "Germany",
    GB: "United Kingdom",
    IN: "India",
    JP: "Japan",
    KR: "South Korea",
    MX: "Mexico",
    RU: "Russia",
    US: "United States of America",
    CA: "Canada",
});

export const CountryColor = {
    FR: "hsl(0, 50%,   40%)",
    DE: "hsl(0, 100%,  50%)",
    GB: "hsl(30, 100%,  50%)",
    IN: "hsl(55, 95%, 50%)",
    JP: "hsl(100, 80%, 50%)",
    KR: "hsl(190, 90%, 50%)",
    MX: "hsl(230, 100%, 50%)",
    RU: "hsl(280, 100%, 50%)",
    US: "hsl(320, 100%, 60%)",
    CA: "hsl(340, 100%, 70%)",
};
